apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: git@github.com:yashrajdighe/argocd-learnings.git
    targetRevision: main
    path: apps # Folder containing child app manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
